### ISSUE TITLE
Doesn't work on macOS

### ISSUE THREAD

**Issue by racemus** [0-wiz-0/trrntzip#1]
I built it on macOS Ventura 13.1 with tools installed from brew. Building was OK, but it doesn't work. No errors, just nothing. Also tried with Java GUI, but no luck.
Great revival though. It would be great to make it work.

**Comment by 0-wiz-0** [comment]
`trrntzip` is a command line application - you need to specify a file or a directory on the command line, e.g.
```
torrentzip file.zip
```
How did you try it?

**Comment by 0-wiz-0** [comment]
I just tried it on macOS, it works:
```
% zip foo Makefile 
  adding: Makefile (deflated 77%)
% ./src/trrntzip foo.zip 
Rezipping - foo.zip
--------------------------------------------------
Adding - Makefile (7394 bytes)...Done
--------------------------------------------------
Rezipped 1 compressed file totaling 7394 bytes.
Execution time 0 hours 0 mins 0 secs

Checked 1 zip file.
  1 file was successfully rezipped.
```
