### ISSUE TITLE
Revival

### ISSUE THREAD

**Issue by denilsonsa** [0-wiz-0/trrntzip#6]
Hi! If this is the revived project that is now maintained, you might want to send a pull request to https://github.com/tikki/trrntzip and to https://github.com/a8bit/trrntzip asking them to point here.

I see there is also a Go implementation, but I don't think it is being maintained either: https://github.com/uwedeportivo/torrentzip

And, if you are in the mood, maybe even make packages for Arch Linux, or contact the maintainers of these old packages to replace them with this repository: https://aur.archlinux.org/packages?K=torrentzip

**Comment by 0-wiz-0** [comment]
Thank you for the suggestion!
I've raised issues at a couple repositories that are based on the original trrntzip.

The Go version is its own thing... a .NET version also exists.

I am not using Arch so I don't even know the social rules for getting updates integrated there. If you know, please request an update - thank you.

**Comment by denilsonsa** [comment]
[AUR](https://wiki.archlinux.org/title/Arch_User_Repository) is the user repository where anyone can submit a PKGBUILD.

[PKGBUILD](https://wiki.archlinux.org/title/PKGBUILD) is a little script with instructions on how to build/install a package. "Official" packages are build from such script and then distributed as binary images. User-contributed packages are just the PKGBUILD script (and some auxiliary file such as patches), which is then used to build the package locally on the user machine.

**Comment by 0-wiz-0** [comment]
Thanks. I'm not using Arch, so I couldn't test any changes, so I'll not provide package updates myself.
